/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiControlRouteImport } from './routes/api/control'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiTapeRouteImport } from './routes/api/tape'
import { Route as ApiTickRouteImport } from './routes/api/tick'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health.live'
import { Route as ApiHealthMigrationsRouteImport } from './routes/api/health.migrations'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health.ready'
import { Route as ApiHealthResearchRouteImport } from './routes/api/health.research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControlRoute = ApiControlRouteImport.update({
  id: '/api/control',
  path: '/api/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeRoute = ApiTapeRouteImport.update({
  id: '/api/tape',
  path: '/api/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTickRoute = ApiTickRouteImport.update({
  id: '/api/tick',
  path: '/api/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthMigrationsRoute = ApiHealthMigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthResearchRoute = ApiHealthResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => ApiHealthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/control': typeof ApiControlRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/quote': typeof ApiQuoteRoute
  '/api/research': typeof ApiResearchRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/tick': typeof ApiTickRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/migrations': typeof ApiHealthMigrationsRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/health/research': typeof ApiHealthResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/control': typeof ApiControlRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/quote': typeof ApiQuoteRoute
  '/api/research': typeof ApiResearchRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/tick': typeof ApiTickRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/migrations': typeof ApiHealthMigrationsRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/health/research': typeof ApiHealthResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/control': typeof ApiControlRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/quote': typeof ApiQuoteRoute
  '/api/research': typeof ApiResearchRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/tick': typeof ApiTickRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/migrations': typeof ApiHealthMigrationsRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/health/research': typeof ApiHealthResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/control'
    | '/api/desk'
    | '/api/health'
    | '/api/quote'
    | '/api/research'
    | '/api/tape'
    | '/api/tick'
    | '/api/health/live'
    | '/api/health/migrations'
    | '/api/health/ready'
    | '/api/health/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/control'
    | '/api/desk'
    | '/api/health'
    | '/api/quote'
    | '/api/research'
    | '/api/tape'
    | '/api/tick'
    | '/api/health/live'
    | '/api/health/migrations'
    | '/api/health/ready'
    | '/api/health/research'
  id:
    | '__root__'
    | '/'
    | '/api/control'
    | '/api/desk'
    | '/api/health'
    | '/api/quote'
    | '/api/research'
    | '/api/tape'
    | '/api/tick'
    | '/api/health/live'
    | '/api/health/migrations'
    | '/api/health/ready'
    | '/api/health/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiControlRoute: typeof ApiControlRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiTapeRoute: typeof ApiTapeRoute
  ApiTickRoute: typeof ApiTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/control': {
      id: '/api/control'
      path: '/api/control'
      fullPath: '/api/control'
      preLoaderRoute: typeof ApiControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape': {
      id: '/api/tape'
      path: '/api/tape'
      fullPath: '/api/tape'
      preLoaderRoute: typeof ApiTapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tick': {
      id: '/api/tick'
      path: '/api/tick'
      fullPath: '/api/tick'
      preLoaderRoute: typeof ApiTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/migrations': {
      id: '/api/health/migrations'
      path: '/migrations'
      fullPath: '/api/health/migrations'
      preLoaderRoute: typeof ApiHealthMigrationsRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/research': {
      id: '/api/health/research'
      path: '/research'
      fullPath: '/api/health/research'
      preLoaderRoute: typeof ApiHealthResearchRouteImport
      parentRoute: typeof ApiHealthRoute
    }
  }
}

interface ApiHealthRouteChildren {
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthMigrationsRoute: typeof ApiHealthMigrationsRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiHealthResearchRoute: typeof ApiHealthResearchRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthMigrationsRoute: ApiHealthMigrationsRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiHealthResearchRoute: ApiHealthResearchRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiControlRoute: ApiControlRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiTapeRoute: ApiTapeRoute,
  ApiTickRoute: ApiTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
