/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiControlRouteImport } from './routes/api/control'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiTapeRouteImport } from './routes/api/tape'
import { Route as ApiTickRouteImport } from './routes/api/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControlRoute = ApiControlRouteImport.update({
  id: '/api/control',
  path: '/api/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeRoute = ApiTapeRouteImport.update({
  id: '/api/tape',
  path: '/api/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTickRoute = ApiTickRouteImport.update({
  id: '/api/tick',
  path: '/api/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/control': typeof ApiControlRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/research': typeof ApiResearchRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/tick': typeof ApiTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/control': typeof ApiControlRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/research': typeof ApiResearchRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/tick': typeof ApiTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/control': typeof ApiControlRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/research': typeof ApiResearchRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/tick': typeof ApiTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/control'
    | '/api/desk'
    | '/api/quote'
    | '/api/research'
    | '/api/tape'
    | '/api/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/control'
    | '/api/desk'
    | '/api/quote'
    | '/api/research'
    | '/api/tape'
    | '/api/tick'
  id:
    | '__root__'
    | '/'
    | '/api/control'
    | '/api/desk'
    | '/api/quote'
    | '/api/research'
    | '/api/tape'
    | '/api/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiControlRoute: typeof ApiControlRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiTapeRoute: typeof ApiTapeRoute
  ApiTickRoute: typeof ApiTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/control': {
      id: '/api/control'
      path: '/api/control'
      fullPath: '/api/control'
      preLoaderRoute: typeof ApiControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape': {
      id: '/api/tape'
      path: '/api/tape'
      fullPath: '/api/tape'
      preLoaderRoute: typeof ApiTapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tick': {
      id: '/api/tick'
      path: '/api/tick'
      fullPath: '/api/tick'
      preLoaderRoute: typeof ApiTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiControlRoute: ApiControlRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiTapeRoute: ApiTapeRoute,
  ApiTickRoute: ApiTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
