import assert from "node:assert/strict";
import { test } from "node:test";
import { applyTape, createDesk } from "./engine.ts";
import { freezeLabels } from "./labels.ts";
import { blankSnapshot, field } from "./providers/normalize.ts";
import type { LedgerRow, MarketTape, TokenLive } from "./types.ts";

function tape(partial: Partial<TokenLive> = {}): MarketTape {
  const now = Date.now();
  const base = blankSnapshot("Mint111111111111111111111111111111111111111", now, now);
  const token: TokenLive = {
    ...base,
    symbol: "TEST",
    name: "Test",
    createdAt: now - 10 * 60_000,
    history: [1, 1.01],
    prevLiq: 80_000,
    prevVolume5m: 12_000,
    prevBuyers: 40,
    rugged: false,
    priceUsd: field(1.02, now, now, "dexscreener"),
    liquidityUsd: field(80_000, now, now, "dexscreener"),
    mcapUsd: field(400_000, now, now, "dexscreener"),
    volume5mUsd: field(12_000, now, now, "dexscreener"),
    ...partial,
  };
  return {
    ingestedAt: now,
    eventTime: now,
    fetchMs: 40,
    solPriceUsd: 180,
    tokens: [token],
    sources: [
      { id: "dexscreener", status: "live", lagMs: 40, lastOkAt: now, detail: "ok" },
      { id: "jupiter", status: "offline", lagMs: null, lastOkAt: null, detail: "down" },
    ],
  };
}

test("pause stops new paper entries but still labels pending paths", () => {
  const t0 = Date.now() - 30_000;
  const desk = createDesk();
  desk.running = false;
  desk.pending = [
    {
      decision_id: "pending-1",
      event_time: t0,
      ingested_at: t0,
      decision_time: t0,
      token: "TEST",
      tokenAddress: "Mint111111111111111111111111111111111111111",
      pair_address: "",
      token_age: 600,
      bucket: "new_launch",
      price: 1,
      market_cap: 400_000,
      liquidity: 80_000,
      volume_1m: null,
      volume_5m: 12_000,
      volume_acceleration: 1,
      buy_sell_imbalance: 0,
      unique_buyers: null,
      unique_sellers: null,
      holder_count: null,
      holder_concentration: null,
      mint_auth: 0,
      freeze_auth: 0,
      entry_impact: 0.004,
      exit_impact: 0.005,
      stressed_exit: 0.03,
      momentum_score: 50,
      flow_score: 50,
      safety_score: 50,
      edge_score: 50,
      regime: "chop",
      strategy_id: "launch_velocity_pullback",
      strategy_version: "3.25",
      governor_result: "vetoed",
      veto_reason: "test",
      proposed_size: 0,
      proposed_entry: 1,
      proposed_stop: 0.9,
      trade_taken: false,
      trade_action: "veto",
      sell_quote_available: true,
      route_status: "ROUTABLE",
      feature_engine_version: "v1.3.0",
      label_definition_version: "labels_v1",
      veto_reason_code: "test",
      research_quality_score: null,
      research_grade: null,
      provider_disagreement: false,
      barrier_10_outcome: null,
      barrier_20_outcome: null,
      barrier_label_confidence: null,
      max_path_gap_seconds: null,
      avg_path_gap_seconds: null,
      path_sample_count: null,
      feature_sources: {},
      gates: [],
      features: {
        tokenAgeS: 600,
        bucket: "new_launch",
        ret1m: 0,
        rv5m: 0.02,
        volAccel: 1,
        usdImbalance: 0,
        holderGrowth5m: 0,
        top10Pct: null,
        liqChange1m: 0,
        liqMcapRatio: 0.2,
        uniqueBuyerShare: 0.5,
        mintAuth: 0,
        freezeAuth: 0,
        sellQuoteAvailable: 1,
        maxDd5m: 0.02,
        entryImpactPct: 0.004,
        exitImpactPct: 0.005,
        snapshotAgeMs: 200,
        priceDisagreement: 0.01,
      },
      path: [{ ts: t0, px: 1, liq: 80_000, sell: 1 }],
      price_after_1m: null,
      price_after_5m: null,
      price_after_15m: null,
      price_after_30m: null,
      price_after_1h: null,
      max_gain_5m: null,
      max_gain_15m: null,
      max_gain_1h: null,
      max_drawdown_5m: null,
      max_drawdown_15m: null,
      max_drawdown_1h: null,
      mfe_1m: null,
      mfe_30m: null,
      mae_1m: null,
      mae_30m: null,
      hit_plus_10_before_minus_10: null,
      hit_plus_20_before_minus_10: null,
      liquidity_collapse: null,
      sell_route_lost: null,
      first_sell_route_loss_at: null,
      sell_route_restored_at: null,
      rug_detected: null,
      simulated_entry: 1.01,
      simulated_exit: null,
      theoretical_return: null,
      net_execution_return: null,
      execution_adjusted_return: null,
      labels_complete: false,
      outcome: "not_taken",
    } satisfies LedgerRow,
  ];
  const next = applyTape(desk, tape());
  assert.equal(next.running, false);
  assert.equal(next.positions.length, 0);
  assert.ok(next.pending[0].path.length >= 2);
});

test("one provider failing does not drop the tape", () => {
  const next = applyTape(createDesk(), tape());
  assert.ok(next.tokens.length >= 1);
  assert.ok(next.sources.some((s) => s.status === "offline"));
  assert.equal(next.realData, true);
});

test("raw observations exist on the tape even with no strategy take", () => {
  const next = applyTape(createDesk(), tape());
  assert.equal(next.positions.length, 0);
  assert.ok(next.tokens.length >= 1);
  assert.ok(next.tokens[0].priceUsd.value);
});

test("pending labels still freeze after a restart-shaped load", () => {
  const t0 = 1_000_000;
  const labeled = freezeLabels(
    {
      ...(applyTape(createDesk(), tape()).pending[0] ?? {
        decision_id: "x",
        event_time: t0,
        ingested_at: t0,
        decision_time: t0,
        token: "T",
        tokenAddress: "M",
        pair_address: "",
        token_age: 1,
        bucket: "new_launch",
        price: 1,
        market_cap: 1,
        liquidity: 50_000,
        volume_1m: null,
        volume_5m: null,
        volume_acceleration: 1,
        buy_sell_imbalance: 0,
        unique_buyers: null,
        unique_sellers: null,
        holder_count: null,
        holder_concentration: null,
        mint_auth: 0,
        freeze_auth: 0,
        entry_impact: 0.004,
        exit_impact: 0.005,
        stressed_exit: 0.03,
        momentum_score: 1,
        flow_score: 1,
        safety_score: 1,
        edge_score: 1,
        regime: "chop",
        strategy_id: "flat",
        strategy_version: "3.25",
        governor_result: "vetoed",
        veto_reason: "x",
        proposed_size: 0,
        proposed_entry: 1,
        proposed_stop: 0.9,
        trade_taken: false,
        trade_action: "veto",
        sell_quote_available: true,
      route_status: "ROUTABLE",
      feature_engine_version: "v1.3.0",
      label_definition_version: "labels_v1",
      veto_reason_code: "test",
      research_quality_score: null,
      research_grade: null,
      provider_disagreement: false,
      barrier_10_outcome: null,
      barrier_20_outcome: null,
      barrier_label_confidence: null,
      max_path_gap_seconds: null,
      avg_path_gap_seconds: null,
      path_sample_count: null,
        feature_sources: {},
        gates: [],
        features: {
          tokenAgeS: 1,
          bucket: "new_launch",
          ret1m: 0,
          rv5m: 0,
          volAccel: 1,
          usdImbalance: 0,
          holderGrowth5m: 0,
          top10Pct: null,
          liqChange1m: 0,
          liqMcapRatio: 1,
          uniqueBuyerShare: 0.5,
          mintAuth: 0,
          freezeAuth: 0,
          sellQuoteAvailable: 1,
          maxDd5m: 0,
          entryImpactPct: 0.004,
          exitImpactPct: 0.005,
          snapshotAgeMs: 1,
          priceDisagreement: 0,
        },
        path: [{ ts: t0, px: 1, liq: 50_000, sell: 1 }],
        price_after_1m: null,
        price_after_5m: null,
        price_after_15m: null,
        price_after_30m: null,
        price_after_1h: null,
        max_gain_5m: null,
        max_gain_15m: null,
        max_gain_1h: null,
        max_drawdown_5m: null,
        max_drawdown_15m: null,
        max_drawdown_1h: null,
        mfe_1m: null,
        mfe_30m: null,
        mae_1m: null,
        mae_30m: null,
        hit_plus_10_before_minus_10: null,
        hit_plus_20_before_minus_10: null,
        liquidity_collapse: null,
        sell_route_lost: null,
        first_sell_route_loss_at: null,
        sell_route_restored_at: null,
        rug_detected: null,
        simulated_entry: 1,
        simulated_exit: null,
        theoretical_return: null,
        net_execution_return: null,
        execution_adjusted_return: null,
        labels_complete: false,
        outcome: "not_taken",
      }),
      price: 1,
      decision_time: t0,
      path: [{ ts: t0, px: 1, liq: 50_000, sell: 1 }, { ts: t0 + 60_000, px: 1.04, liq: 49_000, sell: 1 }],
      labels_complete: false,
    } as LedgerRow,
    t0 + 60_000,
  );
  assert.equal(labeled.price_after_1m, 1.04);
});
